export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct
export CLUTTER_BACKEND="wayland"

export GTK_THEME="Material-Black-Blueberry-3.36"
export XCURSOR_THEME="Adwaita"
# export XCURSOR_SIZE="28"

export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=1
export _JAVA_AWT_WM_NONREPARENTING=1
export SDL_VIDEODRIVER=wayland
export PIPEWIRE_LATENCY="128/48000"

Hyprland
